// irregular verbs
export const verbs = [
    {
        infinitive: 'be',
        german: 'sein',
        thirdPerson: 'is',
        simplePast: 'was',
        pastPerfect: 'been',
        progressive: 'being',
    },
    {
        infinitive: 'beat',
        german: 'schlagen',
        thirdPerson: 'beats',
        simplePast: 'beat',
        pastPerfect: 'beaten',
        progressive: 'beating',
    },
    {
        infinitive: 'become',
        german: 'werden',
        thirdPerson: 'becomes',
        simplePast: 'became',
        pastPerfect: 'become',
        progressive: 'becoming',
    },
    {
        infinitive: 'begin',
        german: 'beginnen',
        thirdPerson: 'begins',
        simplePast: 'began',
        pastPerfect: 'begun',
        progressive: 'beginning',
    },
    {
        infinitive: 'bend',
        german: 'biegen',
        thirdPerson: 'bends',
        simplePast: 'bent',
        pastPerfect: 'bent',
        progressive: 'bending',
    },
    {
        infinitive: 'bet',
        german: 'wetten',
        thirdPerson: 'bets',
        simplePast: 'bet',
        pastPerfect: 'bet',
        progressive: 'betting',
    },
    {
        infinitive: 'bite',
        german: 'beißen',
        thirdPerson: 'bites',
        simplePast: 'bit',
        pastPerfect: 'bitten',
        progressive: 'biting',
    },
    {
        infinitive: 'bleed',
        german: 'bluten',
        thirdPerson: 'bleeds',
        simplePast: 'bled',
        pastPerfect: 'bled',
        progressive: 'bleeding',
    },
    {
        infinitive: 'blow',
        german: 'blasen',
        thirdPerson: 'blows',
        simplePast: 'blew',
        pastPerfect: 'blown',
        progressive: 'blowing',
    },
    {
        infinitive: 'break',
        german: 'brechen',
        thirdPerson: 'breaks',
        simplePast: 'broke',
        pastPerfect: 'broken',
        progressive: 'breaking',
    },
    {
        infinitive: 'bring',
        german: 'bringen',
        thirdPerson: 'brings',
        simplePast: 'brought',
        pastPerfect: 'brought',
        progressive: 'bringing',
    },
    {
        infinitive: 'build',
        german: 'bauen',
        thirdPerson: 'builds',
        simplePast: 'built',
        pastPerfect: 'built',
        progressive: 'building',
    },
    {
        infinitive: 'buy',
        german: 'kaufen',
        thirdPerson: 'buys',
        simplePast: 'bought',
        pastPerfect: 'bought',
        progressive: 'buying',
    },
    {
        infinitive: 'catch',
        german: 'fangen',
        thirdPerson: 'catches',
        simplePast: 'caught',
        pastPerfect: 'caught',
        progressive: 'catching',
    },
    {
        infinitive: 'choose',
        german: 'wählen',
        thirdPerson: 'chooses',
        simplePast: 'chose',
        pastPerfect: 'chosen',
        progressive: 'choosing',
    },
    {
        infinitive: 'come',
        german: 'kommen',
        thirdPerson: 'comes',
        simplePast: 'came',
        pastPerfect: 'come',
        progressive: 'coming',
    },
    {
        infinitive: 'cost',
        german: 'kosten',
        thirdPerson: 'costs',
        simplePast: 'cost',
        pastPerfect: 'cost',
        progressive: 'costing',
    },
    {
        infinitive: 'cut',
        german: 'schneiden',
        thirdPerson: 'cuts',
        simplePast: 'cut',
        pastPerfect: 'cut',
        progressive: 'cutting',
    },
    {
        infinitive: 'do',
        german: 'tun',
        thirdPerson: 'does',
        simplePast: 'did',
        pastPerfect: 'done',
        progressive: 'doing',
    },
    {
        infinitive: 'draw',
        german: 'ziehen',
        thirdPerson: 'draws',
        simplePast: 'drew',
        pastPerfect: 'drawn',
        progressive: 'drawing',
    },
    {
        infinitive: 'dream',
        german: 'träumen',
        thirdPerson: 'dreams',
        simplePast: 'dreamt',
        pastPerfect: 'dreamt',
        progressive: 'dreaming',
    },
    {
        infinitive: 'drink',
        german: 'trinken',
        thirdPerson: 'drinks',
        simplePast: 'drank',
        pastPerfect: 'drunk',
        progressive: 'drinking',
    },
    {
        infinitive: 'drive',
        german: 'fahren',
        thirdPerson: 'drives',
        simplePast: 'drove',
        pastPerfect: 'driven',
        progressive: 'driving',
    },
    {
        infinitive: 'eat',
        german: 'essen',
        thirdPerson: 'eats',
        simplePast: 'ate',
        pastPerfect: 'eaten',
        progressive: 'eating',
    },
    {
        infinitive: 'fall',
        german: 'fallen',
        thirdPerson: 'falls',
        simplePast: 'fell',
        pastPerfect: 'fallen',
        progressive: 'falling',
    },
    {
        infinitive: 'feed',
        german: 'füttern',
        thirdPerson: 'feeds',
        simplePast: 'fed',
        pastPerfect: 'fed',
        progressive: 'feeding',
    },
    {
        infinitive: 'feel',
        german: 'fühlen',
        thirdPerson: 'feels',
        simplePast: 'felt',
        pastPerfect: 'felt',
        progressive: 'feeling',
    },
    {
        infinitive: 'fight',
        german: 'kämpfen',
        thirdPerson: 'fights',
        simplePast: 'fought',
        pastPerfect: 'fought',
        progressive: 'fighting',
    },
    {
        infinitive: 'find',
        german: 'finden',
        thirdPerson: 'finds',
        simplePast: 'found',
        pastPerfect: 'found',
        progressive: 'finding',
    },
    {
        infinitive: 'fly',
        german: 'fliegen',
        thirdPerson: 'flies',
        simplePast: 'flew',
        pastPerfect: 'flown',
        progressive: 'flying',
    },
    {
        infinitive: 'forget',
        german: 'vergessen',
        thirdPerson: 'forgets',
        simplePast: 'forgot',
        pastPerfect: 'forgotten',
        progressive: 'forgetting',
    },
    {
        infinitive: 'forgive',
        german: 'vergeben',
        thirdPerson: 'forgives',
        simplePast: 'forgave',
        pastPerfect: 'forgiven',
        progressive: 'forgiving',
    },
    {
        infinitive: 'freeze',
        german: 'frieren',
        thirdPerson: 'freezes',
        simplePast: 'froze',
        pastPerfect: 'frozen',
        progressive: 'freezing',
    },
    {
        infinitive: 'get',
        german: 'bekommen',
        thirdPerson: 'gets',
        simplePast: 'got',
        pastPerfect: 'got',
        progressive: 'getting',
    },
    {
        infinitive: 'give',
        german: 'geben',
        thirdPerson: 'gives',
        simplePast: 'gave',
        pastPerfect: 'given',
        progressive: 'giving',
    },
    {
        infinitive: 'go',
        german: 'gehen',
        thirdPerson: 'goes',
        simplePast: 'went',
        pastPerfect: 'gone',
        progressive: 'going',
    },
    {
        infinitive: 'grow',
        german: 'wachsen',
        thirdPerson: 'grows',
        simplePast: 'grew',
        pastPerfect: 'grown',
        progressive: 'growing',
    },
    {
        infinitive: 'hang',
        german: 'hängen',
        thirdPerson: 'hangs',
        simplePast: 'hung',
        pastPerfect: 'hung',
        progressive: 'hanging',
    },
    {
        infinitive: 'have',
        german: 'haben',
        thirdPerson: 'has',
        simplePast: 'had',
        pastPerfect: 'had',
        progressive: 'having',
    },
    {
        infinitive: 'hear',
        german: 'hören',
        thirdPerson: 'hears',
        simplePast: 'heard',
        pastPerfect: 'heard',
        progressive: 'hearing',
    },
    {
        infinitive: 'hide',
        german: 'verstecken',
        thirdPerson: 'hides',
        simplePast: 'hid',
        pastPerfect: 'hidden',
        progressive: 'hiding',
    },
    {
        infinitive: 'hit',
        german: 'treffen',
        thirdPerson: 'hits',
        simplePast: 'hit',
        pastPerfect: 'hit',
        progressive: 'hitting',
    },
    {
        infinitive: 'hold',
        german: 'halten',
        thirdPerson: 'holds',
        simplePast: 'held',
        pastPerfect: 'held',
        progressive: 'holding',
    },
    {
        infinitive: 'hurt',
        german: 'verletzen',
        thirdPerson: 'hurts',
        simplePast: 'hurt',
        pastPerfect: 'hurt',
        progressive: 'hurting',
    },
    {
        infinitive: 'keep',
        german: 'halten',
        thirdPerson: 'keeps',
        simplePast: 'kept',
        pastPerfect: 'kept',
        progressive: 'keeping',
    },
    {
        infinitive: 'know',
        german: 'wissen',
        thirdPerson: 'knows',
        simplePast: 'knew',
        pastPerfect: 'known',
        progressive: 'knowing',
    },
    {
        infinitive: 'lay',
        german: 'legen',
        thirdPerson: 'lays',
        simplePast: 'laid',
        pastPerfect: 'laid',
        progressive: 'laying',
    },
    {
        infinitive: 'lead',
        german: 'führen',
        thirdPerson: 'leads',
        simplePast: 'led',
        pastPerfect: 'led',
        progressive: 'leading',
    },
    {
        infinitive: 'learn',
        german: 'lernen',
        thirdPerson: 'learns',
        simplePast: 'learnt',
        pastPerfect: 'learnt',
        progressive: 'learning',
    },
    {
        infinitive: 'leave',
        german: 'verlassen',
        thirdPerson: 'leaves',
        simplePast: 'left',
        pastPerfect: 'left',
        progressive: 'leaving',
    },
    {
        infinitive: 'lend',
        german: 'leihen',
        thirdPerson: 'lends',
        simplePast: 'lent',
        pastPerfect: 'lent',
        progressive: 'lending',
    },
    {
        infinitive: 'let',
        german: 'lassen',
        thirdPerson: 'lets',
        simplePast: 'let',
        pastPerfect: 'let',
        progressive: 'letting',
    },
    {
        infinitive: 'lie',
        german: 'liegen',
        thirdPerson: 'lies',
        simplePast: 'lay',
        pastPerfect: 'lain',
        progressive: 'lying',
    },
    {
        infinitive: 'lose',
        german: 'verlieren',
        thirdPerson: 'loses',
        simplePast: 'lost',
        pastPerfect: 'lost',
        progressive: 'losing',
    },
    {
        infinitive: 'make',
        german: 'machen',
        thirdPerson: 'makes',
        simplePast: 'made',
        pastPerfect: 'made',
        progressive: 'making',
    },
    {
        infinitive: 'mean',
        german: 'bedeuten',
        thirdPerson: 'means',
        simplePast: 'meant',
        pastPerfect: 'meant',
        progressive: 'meaning',
    },
    {
        infinitive: 'meet',
        german: 'treffen',
        thirdPerson: 'meets',
        simplePast: 'met',
        pastPerfect: 'met',
        progressive: 'meeting',
    },
    {
        infinitive: 'pay',
        german: 'zahlen',
        thirdPerson: 'pays',
        simplePast: 'paid',
        pastPerfect: 'paid',
        progressive: 'paying',
    },
    {
        infinitive: 'put',
        german: 'legen',
        thirdPerson: 'puts',
        simplePast: 'put',
        pastPerfect: 'put',
        progressive: 'putting',
    },
    {
        infinitive: 'read',
        german: 'lesen',
        thirdPerson: 'reads',
        simplePast: 'read',
        pastPerfect: 'read',
        progressive: 'reading',
    },
    {
        infinitive: 'ride',
        german: 'reiten',
        thirdPerson: 'rides',
        simplePast: 'rode',
        pastPerfect: 'ridden',
        progressive: 'riding',
    },
    {
        infinitive: 'ring',
        german: 'klingeln',
        thirdPerson: 'rings',
        simplePast: 'rang',
        pastPerfect: 'rung',
        progressive: 'ringing',
    },
    {
        infinitive: 'rise',
        german: 'steigen',
        thirdPerson: 'rises',
        simplePast: 'rose',
        pastPerfect: 'risen',
        progressive: 'rising',
    },
    {
        infinitive: 'run',
        german: 'rennen',
        thirdPerson: 'runs',
        simplePast: 'ran',
        pastPerfect: 'run',
        progressive: 'running',
    },
    {
        infinitive: 'say',
        german: 'sagen',
        thirdPerson: 'says',
        simplePast: 'said',
        pastPerfect: 'said',
        progressive: 'saying',
    },
    {
        infinitive: 'see',
        german: 'sehen',
        thirdPerson: 'sees',
        simplePast: 'saw',
        pastPerfect: 'seen',
        progressive: 'seeing',
    },
    {
        infinitive: 'sell',
        german: 'verkaufen',
        thirdPerson: 'sells',
        simplePast: 'sold',
        pastPerfect: 'sold',
        progressive: 'selling',
    },
    {
        infinitive: 'send',
        german: 'senden',
        thirdPerson: 'sends',
        simplePast: 'sent',
        pastPerfect: 'sent',
        progressive: 'sending',
    },
    {
        infinitive: 'set',
        german: 'stellen',
        thirdPerson: 'sets',
        simplePast: 'set',
        pastPerfect: 'set',
        progressive: 'setting',
    },
    {
        infinitive: 'sew',
        german: 'nähen',
        thirdPerson: 'sews',
        simplePast: 'sewed',
        pastPerfect: 'sewn',
        progressive: 'sewing',
    },
    {
        infinitive: 'shake',
        german: 'schütteln',
        thirdPerson: 'shakes',
        simplePast: 'shook',
        pastPerfect: 'shaken',
        progressive: 'shaking',
    },
    {
        infinitive: 'shine',
        german: 'leuchten',
        thirdPerson: 'shines',
        simplePast: 'shone',
        pastPerfect: 'shone',
        progressive: 'shining',
    },
    {
        infinitive: 'shoot',
        german: 'schießen',
        thirdPerson: 'shoots',
        simplePast: 'shot',
        pastPerfect: 'shot',
        progressive: 'shooting',
    },
    {
        infinitive: 'show',
        german: 'zeigen',
        thirdPerson: 'shows',
        simplePast: 'showed',
        pastPerfect: 'shown',
        progressive: 'showing',
    },
    {
        infinitive: 'shut',
        german: 'schließen',
        thirdPerson: 'shuts',
        simplePast: 'shut',
        pastPerfect: 'shut',
        progressive: 'shutting',
    },
    {
        infinitive: 'sing',
        german: 'singen',
        thirdPerson: 'sings',
        simplePast: 'sang',
        pastPerfect: 'sung',
        progressive: 'singing',
    },
    {
        infinitive: 'sink',
        german: 'sinken',
        thirdPerson: 'sinks',
        simplePast: 'sank',
        pastPerfect: 'sunk',
        progressive: 'sinking',
    },
    {
        infinitive: 'sit',
        german: 'sitzen',
        thirdPerson: 'sits',
        simplePast: 'sat',
        pastPerfect: 'sat',
        progressive: 'sitting',
    },
    {
        infinitive: 'sleep',
        german: 'schlafen',
        thirdPerson: 'sleeps',
        simplePast: 'slept',
        pastPerfect: 'slept',
        progressive: 'sleeping',
    },
    {
        infinitive: 'speak',
        german: 'sprechen',
        thirdPerson: 'speaks',
        simplePast: 'spoke',
        pastPerfect: 'spoken',
        progressive: 'speaking',
    },
    {
        infinitive: 'spend',
        german: 'verbringen',
        thirdPerson: 'spends',
        simplePast: 'spent',
        pastPerfect: 'spent',
        progressive: 'spending',
    },
    {
        infinitive: 'spill',
        german: 'verschütten',
        thirdPerson: 'spills',
        simplePast: 'spilled',
        pastPerfect: 'spilled',
        progressive: 'spilling',
    },
    {
        infinitive: 'spoil',
        german: 'verderben',
        thirdPerson: 'spoils',
        simplePast: 'spoiled',
        pastPerfect: 'spoiled',
        progressive: 'spoiling',
    },
    {
        infinitive: 'spread',
        german: 'ausbreiten',
        thirdPerson: 'spreads',
        simplePast: 'spread',
        pastPerfect: 'spread',
        progressive: 'spreading',
    },
    {
        infinitive: 'stand',
        german: 'stehen',
        thirdPerson: 'stands',
        simplePast: 'stood',
        pastPerfect: 'stood',
        progressive: 'standing',
    },
    {
        infinitive: 'steal',
        german: 'stehlen',
        thirdPerson: 'steals',
        simplePast: 'stole',
        pastPerfect: 'stolen',
        progressive: 'stealing',
    },
    {
        infinitive: 'stick',
        german: 'kleben',
        thirdPerson: 'sticks',
        simplePast: 'stuck',
        pastPerfect: 'stuck',
        progressive: 'sticking',
    },
    {
        infinitive: 'sting',
        german: 'stechen',
        thirdPerson: 'stings',
        simplePast: 'stung',
        pastPerfect: 'stung',
        progressive: 'stinging',
    },
    {
        infinitive: 'strike',
        german: 'schlagen',
        thirdPerson: 'strikes',
        simplePast: 'struck',
        pastPerfect: 'struck',
        progressive: 'striking',
    },
    {
        infinitive: 'swear',
        german: 'schwören',
        thirdPerson: 'swears',
        simplePast: 'swore',
        pastPerfect: 'sworn',
        progressive: 'swearing',
    },
    {
        infinitive: 'sweep',
        german: 'kehren',
        thirdPerson: 'sweeps',
        simplePast: 'swept',
        pastPerfect: 'swept',
        progressive: 'sweeping',
    },
    {
        infinitive: 'swim',
        german: 'schwimmen',
        thirdPerson: 'swims',
        simplePast: 'swam',
        pastPerfect: 'swum',
        progressive: 'swimming',
    },
    {
        infinitive: 'swing',
        german: 'schaukeln',
        thirdPerson: 'swings',
        simplePast: 'swung',
        pastPerfect: 'swung',
        progressive: 'swinging',
    },
    {
        infinitive: 'take',
        german: 'nehmen',
        thirdPerson: 'takes',
        simplePast: 'took',
        pastPerfect: 'taken',
        progressive: 'taking',
    },
    {
        infinitive: 'teach',
        german: 'lehren',
        thirdPerson: 'teaches',
        simplePast: 'taught',
        pastPerfect: 'taught',
        progressive: 'teaching',
    },
    {
        infinitive: 'tear',
        german: 'zerreißen',
        thirdPerson: 'tears',
        simplePast: 'tore',
        pastPerfect: 'torn',
        progressive: 'tearing',
    },
    {
        infinitive: 'tell',
        german: 'erzählen',
        thirdPerson: 'tells',
        simplePast: 'told',
        pastPerfect: 'told',
        progressive: 'telling',
    },
    {
        infinitive: 'think',
        german: 'denken',
        thirdPerson: 'thinks',
        simplePast: 'thought',
        pastPerfect: 'thought',
        progressive: 'thinking',
    },
    {
        infinitive: 'throw',
        german: 'werfen',
        thirdPerson: 'throws',
        simplePast: 'threw',
        pastPerfect: 'thrown',
        progressive: 'throwing',
    },
    {
        infinitive: 'understand',
        german: 'verstehen',
        thirdPerson: 'understands',
        simplePast: 'understood',
        pastPerfect: 'understood',
        progressive: 'understanding',
    },
    {
        infinitive: 'wake',
        german: 'wecken',
        thirdPerson: 'wakes',
        simplePast: 'woke',
        pastPerfect: 'woken',
        progressive: 'waking',
    },
    {
        infinitive: 'wear',
        german: 'tragen',
        thirdPerson: 'wears',
        simplePast: 'wore',
        pastPerfect: 'worn',
        progressive: 'wearing',
    },
    {
        infinitive: 'win',
        german: 'gewinnen',
        thirdPerson: 'wins',
        simplePast: 'won',
        pastPerfect: 'won',
        progressive: 'winning',
    },
    {
        infinitive: 'write',
        german: 'schreiben',
        thirdPerson: 'writes',
        simplePast: 'wrote',
        pastPerfect: 'written',
        progressive: 'writing',
    },
];
